### PR TITLE
Make quiz checks more informative and user friendly

### LINKED ISSUE #2: Test out the quiz checking functions
There are functions included in this package for checking quiz formatting. I don't know much about them right now, but there are two things I will plan on doing with these functions: 

1) Try them out -- see if/how they work and also find out how they do NOT work. 
2) Document more where necessary. This may include documentation here (not sure where @muschellij2 left off on this), but also includes adding guidance in the Leanpub template repo's getting_started.md that will be more specifically tailored to those situations (Related to https://github.com/jhudsl/DaSL_Course_Template_Leanpub/issues/25).

### PR DESCRIPTION
**Pull request by cansavvy**
This will close #2 

Adds here: 

- `quiz.R` has been revamped. 
- quiz checks are added as an option to `bookdown_to_leanpub()`
- More examples and documentation are added to everything 
- Bad and good quiz examples for testing purposes are added to `extData`

What is left to be done: 
- Add examples and vignettes!

### CODE REVIEW

**Comment by cansavvy** [comment]
The installation is failing but the errors are not clear to me just says that: ```ERROR: hard-coded installation path: please report to the package maintainer and use ‘--no-staged-install’```

I'm trying to use then no-stage-install option to see if that makes it work, but I need to look more closely into the implications of that option.

File: R/quiz.R [hunk 1]
```diff
@@ -1,81 +1,182 @@
...
-# Make sure choose answers is > than the number of answers you give. lol
-# Make sure that if you say "choose-answers" you use the C) m) o) notation
-# Make sure if you don't use choose answers but instead use : a, b,c,d you delete the "choose-answers" tag
-# Don't have exclamation points in answers.
-# Make sure there's at least one right answer!
-# Make sure the top of the quiz tag looks something like: {quiz, id: quiz_why_doc, attempts: 10}
-# Make sure all quizzes are listed in Book.txt (I think John made a check for this part already).
+# These will be existing paths to grab from for examples
+#' @export
+good_quiz_path <- list.files(pattern = "quiz_good.md",
```
Comment (cansavvy) [inline R/quiz.R:4]: I suspect this is part of the problem because its' trying to run this before `leanbuild` is actually installed.

**Comment by cansavvy** [comment]
It's working. All is documented. I'm tired. Merging this before it gets more out of hand.
